name: Hello world

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - name: Current Date
        run: date
      - name: Current Directory
        run: ls -l
